### 1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [5]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from 'c:\\users\\gabfp\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\numpy\\version.py'>
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
* Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [6]:
a = np.random.rand(2,3,5)

### 4. Print a.

In [7]:
print(a)

[[[0.59105262 0.55279806 0.24973491 0.69135163 0.03367317]
  [0.788302   0.97239889 0.74395395 0.19878456 0.52836208]
  [0.68374368 0.31909149 0.48855909 0.14462006 0.45092485]]

 [[0.34456658 0.38646306 0.14122017 0.89024829 0.22076367]
  [0.26671081 0.55080311 0.44735126 0.08161103 0.17786379]
  [0.43667585 0.30168813 0.75973502 0.63041852 0.08480641]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [9]:
b = np.ones((5,2,3))

### 6. Print b.

In [10]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### 7. Do a and b have the same size? How do you prove that in Python code?

In [14]:
a.itemsize == b.itemsize

True

### 8. Are you able to add a and b? Why or why not?

In [15]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [17]:
c = b.reshape(a.shape)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [24]:
d = np.add(a,c)

In [25]:
d

array([[[1.59105262, 1.55279806, 1.24973491, 1.69135163, 1.03367317],
        [1.788302  , 1.97239889, 1.74395395, 1.19878456, 1.52836208],
        [1.68374368, 1.31909149, 1.48855909, 1.14462006, 1.45092485]],

       [[1.34456658, 1.38646306, 1.14122017, 1.89024829, 1.22076367],
        [1.26671081, 1.55080311, 1.44735126, 1.08161103, 1.17786379],
        [1.43667585, 1.30168813, 1.75973502, 1.63041852, 1.08480641]]])

### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
print(a)
print("<------------------------------------------------------>")
print(d)

[[[0.59105262 0.55279806 0.24973491 0.69135163 0.03367317]
  [0.788302   0.97239889 0.74395395 0.19878456 0.52836208]
  [0.68374368 0.31909149 0.48855909 0.14462006 0.45092485]]

 [[0.34456658 0.38646306 0.14122017 0.89024829 0.22076367]
  [0.26671081 0.55080311 0.44735126 0.08161103 0.17786379]
  [0.43667585 0.30168813 0.75973502 0.63041852 0.08480641]]]
<------------------------------------------------------>
[[[1.59105262 1.55279806 1.24973491 1.69135163 1.03367317]
  [1.788302   1.97239889 1.74395395 1.19878456 1.52836208]
  [1.68374368 1.31909149 1.48855909 1.14462006 1.45092485]]

 [[1.34456658 1.38646306 1.14122017 1.89024829 1.22076367]
  [1.26671081 1.55080311 1.44735126 1.08161103 1.17786379]
  [1.43667585 1.30168813 1.75973502 1.63041852 1.08480641]]]


### 12. Multiply a and c. Assign the result to e.

In [32]:
e = np.multiply(a,c)

### 13. Does e equal to a? Why or why not?

In [34]:
print(e == a)
print("because c have all values set to 1")

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
because c have all values set to 1


### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [35]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [36]:
f = np.empty(d.shape)


### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [44]:
for i in np.nditer(d):
    x,y,z = np.where(d == i)
    if i == d_max:
        f[x,y,z] = 100
    elif i > d_mean and i < d_max:
        f[x,y,z] = 75
    elif i == d_mean:
        f[x,y,z] = 50
    elif i > d_min and i <d_mean:
        f[x,y,z] = 25
    elif i == d_min:
        f[x,y,z] = 0
      
print(d)
print("<------------------------------>")
print(f)

[[[1.59105262 1.55279806 1.24973491 1.69135163 1.03367317]
  [1.788302   1.97239889 1.74395395 1.19878456 1.52836208]
  [1.68374368 1.31909149 1.48855909 1.14462006 1.45092485]]

 [[1.34456658 1.38646306 1.14122017 1.89024829 1.22076367]
  [1.26671081 1.55080311 1.44735126 1.08161103 1.17786379]
  [1.43667585 1.30168813 1.75973502 1.63041852 1.08480641]]]
<------------------------------>
[[[ 75.  75.  25.  75.   0.]
  [ 75. 100.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  25.  25.  75.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]]]


### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


In [52]:
g = np.empty(d.shape)
g.dtype
for i in np.nditer(d):
    x,y,z = np.where(d == i)
    if i == d_max:
        g[x,y,z] = "A"
    elif i > d_mean and i < d_max:
        g[x,y,z] = "B"
    elif i == d_mean:
        g[x,y,z] = "C"
    elif i > d_min and i <d_mean:
        g[x,y,z] = "D"
    elif i == d_min:
        g[x,y,z] = "E"
      
print(d)
print("<------------------------------>")
print(f)

ValueError: could not convert string to float: 'B'